
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pftdatabase
      MYSQL_USER: pftdatabase
      MYSQL_PASSWORD: pftdatabase
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  php:
    build:
      context: ./PFTbackend
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./PFTbackend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80" # Laravel accessible at http://localhost:8000
    volumes:
      - ./PFTbackend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./PFTbackend:/var/www/html:ro
    depends_on:
      - php
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:


networks:
  backend:
    driver: bridge
